server:
  port: 9191

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/v1/cart,/api/v1/cart/**
        - id: offer-service
          uri: lb://offer-service
          predicates:
            - Path=/api/v1/offer,/api/v1/offer/**, /api/v1/discount,/api/v1/discount/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**, /api/v1/product


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
